# **Data Wrangling and Preparation for Time Series**

Data wrangling is the art of transformation and mapping raw data
into valuable information with the help of preprocessing strategies.

The functions and methods introduced here have a lot more functionalities than covered here. You can explore them in more detail at the official Pandas and Pandasql sites.

# **Loading Data into Pandas**

#Load data using CSV

In [ ]:
import pandas as pd
df = pd.read_csv(r'/content/Air Quality.csv')
df.head(5)

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.60,0.48,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
1,2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2,2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.6,32.78,6.35,6.38,0.47,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.1,0.0,NaN

# **Exploring Pandasql and Pandas Side by Side**

*   Pandasql is a Python framework for running SQL queries on Pandas DataFrames.
*   It helps us to query Pandas DataFrames using SQL syntax.
*   It provides a SQL interface to perform data wrangling on a Pandas DataFrame.
*   Pandasql helps analysts and data engineers who are masters of SQL to transition into Python (Pandas) smoothly.

**PandaSQL accepts 2 paramaeters: a SQL query string and a set of session/environment variables (locals() or globals()).**

#Selecting the Top Five Records

In [ ]:
!pip install -q pandasql

  Preparing metadata (setup.py) ... done
  Building wheel for pandasql (setup.py) ... done

In [ ]:
#By using Pandas
df.head(5)

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.60,0.48,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
1,2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2,2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.6,32.78,6.35,6.38,0.47,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.1,0.0,NaN

In [ ]:
#By using Pandasql
from pandasql import sqldf

Query_string = """ select * from df limit 5 """
sqldf(Query_string, globals())

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.60,0.48,...,33.43,71.67,2.30,226.33,123.67,None,-0.1,0.1,0.0,23.05
1,2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,...,33.70,70.00,2.50,223.00,186.00,None,-0.1,0.1,0.0,NaN
2,2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
3,2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
4,2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.6,32.78,6.35,6.38,0.47,...,33.57,63.50,1.88,223.00,240.50,None,-0.1,0.1,0.0,NaN

#Applying Filter

This is also known as subsetting data or drill-down data.

In [ ]:
#By using Pandas
df[(df['Ozone (ug/m3)'] >=30) & (df['Ozone (ug/m3)'] <=45)].head()

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
766,2016-08-02 08:00:00,2016-08-02 09:00:00,18.00,57.0,8.23,32.97,22.17,6.80,3.70,0.25,...,32.93,72.33,2.87,56.67,59.33,NaN,-0.10,0.1,0.0,20.20
767,2016-08-02 09:00:00,2016-08-02 10:00:00,11.25,58.0,6.33,29.45,19.05,7.28,3.78,0.17,...,32.88,71.00,2.85,86.50,112.25,NaN,-0.10,0.1,0.0,20.57
836,2016-08-05 06:00:00,2016-08-05 07:00:00,3.75,22.5,8.77,37.95,25.03,5.27,5.62,0.27,...,32.77,76.00,1.90,197.25,13.75,NaN,0.68,0.1,0.0,20.20
846,2016-08-05 16:00:00,2016-08-05 17:00:00,7.00,46.0,12.23,40.80,29.03,5.97,7.30,0.39,...,33.33,65.00,1.93,224.00,53.33,NaN,0.20,0.1,0.0,24.67
928,2016-08-09 02:00:00,2016-08-09 03:00:00,2.75,37.5,2.80,32.40,17.87,6.02,2.95,0.12,...,33.10,71.25,1.87,156.50,7.00,NaN,0.32,0.1,0.0,NaN

In [ ]:
#By using Pandasql
# Query_string = """ select * from df where AT (degree C) >=20 and AT (degree C) <=40 """
Query_string = """SELECT * FROM df WHERE [AT (degree C)] >= 20 AND [AT (degree C)] <= 40"""

sqldf(Query_string, globals())

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.00,17.67,39.20,32.33,7.07,6.60,0.48,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.10,0.10,0.0,23.05
1,2016-07-01 15:00:00,2016-07-01 16:00:00,15.25,59.50,24.30,45.12,40.12,6.65,6.53,0.51,...,33.55,63.75,1.40,213.25,152.25,NaN,-0.10,0.10,0.0,25.60
2,2016-07-01 16:00:00,2016-07-01 17:00:00,11.67,60.00,26.73,49.10,43.80,6.93,5.70,0.46,...,33.57,64.00,1.50,208.67,92.67,NaN,-0.10,0.23,0.0,25.70
3,2016-07-01 17:00:00,2016-07-01 18:00:00,11.75,57.50,19.10,46.33,36.82,8.12,6.23,0.44,...,33.48,64.00,1.95,222.75,35.00,NaN,-0.10,0.10,0.0,25.15
4,2016-07-01 18:00:00,2016-07-01 19:00:00,18.00,57.75,14.50,44.20,32.33,7.78,6.07,0.45,...,33.23,63.75,2.15,220.75,14.00,NaN,-0.10,0.10,0.0,24.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20293,2019-12-25 12:00:00,2019-12-25 13:00:00,19.00,78.00,9.70,23.73,20.53,19.97,4.90,0.49,...,28.47,77.75,1.57,226.00,122.25,NaN,-0.10,0.10,0.0,20.82
20294,2019-12-25 13:00:00,2019-12-25 14:00:00,23.00,76.50,8.68,21.07,18.28,20.05,4.32,0.43,...,27.95,77.50,1.53,226.50,17.75,NaN,-0.08,0.12,0.0,20.75
20295,2019-12-25 14:00:00,2019-12-25 15:00:00,33.25,68.50,9.15,17.40,16.62,19.52,4.95,0.34,...,27.77,75.75,1.57,253.50,1.00,NaN,-0.05,0.10,0.0,20.82
20296,2019-12-25 15:00:00,2019-12-25 16:00:00,26.75,60.75,12.25,20.27,20.72,20.00,4.42,0.39,...,27.75,78.75,1.45,233.00,1.00,NaN,-0.08,0.10,0.0,20.43
20297,2019-12-25 16:00:00,2019-12-25 17:00:00,25.75,69.50,9.15,20.15,18.17,19.73,4.45,0.41,...,27.72,81.25,1.35,239.50,1.00,NaN,-0.08,0.10,0.0,20.02

In [ ]:
df.columns

Index(['From Date', 'To Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)',
       'NO2 (ug/m3)', 'NOx (ppb)', 'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)',
       'Ozone (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Temp (degree C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'SR (W/mt2)',
       'BP (mmHg)', 'VWS (m/s)', 'Xylene (ug/m3)', 'RF (mm)', 'AT (degree C)'],
      dtype='object')

# Distince(Unique)

In [ ]:
#By using Pandas
df['BP (mmHg)'].unique()

array([    nan,  925.25,  950.75,  952.5 , 1050.  ,  744.  ,  752.  ,
        750.5 ,  750.  ,  749.  ,  748.25,  747.75,  749.25,  750.25,
        751.75,  752.75,  751.  ,  748.  ,  748.5 ,  751.5 ,  752.5 ,
        752.25,  748.75,  753.  ,  747.25,  747.5 ,  751.25,  753.25,
        750.75,  749.75,  749.5 ,  753.5 ,  754.  ,  753.75,  747.  ,
        745.75,  745.  ,  744.75,  744.25,  745.25,  746.75,  746.  ,
        746.5 ,  745.5 ,  754.75,  755.5 ,  755.  ,  754.25,  755.25,
        756.  ,  754.5 ,  757.  ,  757.75,  758.  ,  757.5 ,  756.75,
        756.25,  756.5 ,  758.25,  759.  ,  757.67,  757.25,  755.75,
        758.5 ,  758.75,  759.75,  760.25,  760.75,  759.67,  759.5 ,
        760.  ,  760.5 ,  761.75,  762.75,  761.  ,  761.5 ,  762.  ,
        761.25,  763.  ,  762.25,  762.5 ,  759.25,  752.67,  746.33,
        754.67,  758.33,  754.33,  779.  ,  763.75,  851.  ,  897.  ,
        740.  ,  725.  ,  741.  ,  855.  ,  742.  ,  817.  ,  790.  ])

In [ ]:
#By using Pandasql
Query_string = """ select distinct [BP (mmHg)] from df;"""
sqldf(Query_string, globals())

    BP (mmHg)
0         NaN
1      925.25
2      950.75
3      952.50
4     1050.00
..        ...
93     741.00
94     855.00
95     742.00
96     817.00
97     790.00

[98 rows x 1 columns]

# IN

Checks whether values are present in the sequence.

In [ ]:
#By using Pandas
df[df['BP (mmHg)'].isin([700,750,800])].tail()

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
9908,2017-08-18 06:00:00,2017-08-18 07:00:00,13.00,47.50,8.48,54.98,36.15,NaN,4.02,0.25,...,32.72,86.25,1.80,256.00,3.0,750.0,0.2,0.0,0.0,19.97
9921,2017-08-18 19:00:00,2017-08-18 20:00:00,16.75,81.00,17.15,87.67,60.55,NaN,1.90,0.40,...,32.30,78.75,0.85,267.50,3.0,750.0,0.0,0.0,0.0,21.80
9927,2017-08-19 01:00:00,2017-08-19 02:00:00,14.25,53.25,3.62,51.80,30.50,NaN,4.55,0.28,...,32.30,79.75,2.07,173.75,3.0,750.0,0.1,0.0,0.0,21.25
9977,2017-08-21 03:00:00,2017-08-21 04:00:00,6.00,22.00,4.70,54.72,32.90,NaN,0.43,0.23,...,32.57,83.00,1.40,229.75,3.0,750.0,0.1,0.0,0.0,20.25
9978,2017-08-21 04:00:00,2017-08-21 05:00:00,5.50,21.00,3.75,49.80,29.53,NaN,2.00,0.19,...,32.18,83.00,1.30,253.00,3.0,750.0,0.1,0.0,0.0,20.20

In [ ]:
#By using Pandasql
Query_string = """ select * from df where [BP (mmHg)] in(700,750,800);"""
sqldf(Query_string, globals())

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2017-07-17 13:00:00,2017-07-17 14:00:00,17.00,36.75,3.00,24.55,15.48,None,NaN,0.32,...,33.85,69.25,2.17,184.75,79.75,750.0,0.20,0.00,0.0,22.80
1,2017-07-18 06:00:00,2017-07-18 07:00:00,11.00,36.25,2.12,19.28,12.03,None,3.90,0.23,...,32.70,76.00,2.82,185.00,3.00,750.0,0.18,0.00,0.0,20.78
2,2017-07-18 12:00:00,2017-07-18 13:00:00,14.75,39.25,2.30,21.70,13.38,None,5.15,0.39,...,32.58,65.25,2.77,131.00,103.75,750.0,0.20,0.00,0.0,23.50
3,2017-07-18 13:00:00,2017-07-18 14:00:00,13.75,45.00,3.12,24.72,15.65,None,3.62,0.46,...,33.10,64.50,2.47,130.50,71.50,750.0,0.18,0.00,0.0,23.65
4,2017-07-19 05:00:00,2017-07-19 06:00:00,10.25,37.75,2.22,19.62,12.22,None,2.50,0.23,...,31.92,76.75,2.38,219.50,3.00,750.0,0.13,0.00,0.0,20.73
5,2017-07-20 02:00:00,2017-07-20 03:00:00,6.00,34.50,6.77,29.70,21.30,None,6.43,0.25,...,31.45,78.25,2.38,296.25,3.00,750.0,0.10,0.00,0.0,20.90
6,2017-07-20 03:00:00,2017-07-20 04:00:00,16.00,34.00,4.58,24.58,16.80,None,6.23,0.23,...,31.75,78.25,2.35,286.50,3.00,750.0,0.10,0.00,0.0,20.75
7,2017-07-20 04:00:00,2017-07-20 05:00:00,12.50,35.25,3.35,22.03,14.42,None,3.50,0.20,...,31.60,79.00,2.12,295.25,3.00,750.0,0.08,0.00,0.0,20.63
8,2017-07-20 05:00:00,2017-07-20 06:00:00,11.50,30.75,4.10,24.78,16.50,None,2.77,0.23,...,31.55,80.00,2.15,281.75,3.00,750.0,0.08,0.00,0.0,20.40
9,2017-07-20 18:00:00,2017-07-20 19:00:00,14.25,48.25,6.85,41.45,27.60,None,NaN,0.57,...,45.93,56.25,1.75,216.75,3.00,750.0,NaN,0.00,0.0,25.25
10,2017-08-03 03:00:00,2017-08-03 04:00:00,12.00,49.00,2.10,26.53,15.80,None,2.93,0.32,...,33.02,75.00,1.30,116.75,3.00,750.0,0.05,0.28,0.0,22.35
11,2017-08-03 04:00:00,2017-08-03 05:00:00,11.25,39.25,2.10,23.17,14.05,None,4.50,0.26,...,32.52,69.75,1.58,119.50,3.00,750.0,0.13,0.00,0.0,22.22
12,2017-08-03 13:00:00,2017-08-03 14:00:00,22.00,54.50,11.20,33.15,26.72,None,3.52,0.54,...,33.50,58.50,1.48,201.50,305.50,750.0,0.10,0.00,0.0,25.75
13,2017-08-04 08:00:00,2017-08-04 09:00:00,13.75,37.75,9.88,30.17,24.10,None,8.25,0.21,...,32.93,72.25,2.15,133.25,98.50,750.0,0.20,0.00,0.0,22.50
14,2017-08-04 11:00:00,2017-08-04 12:00:00,12.00,37.25,8.35,26.02,20.63,None,NaN,0.36,...,34.38,63.25,1.60,178.00,240.25,750.0,0.15,0.00,0.0,25.07
15,2017-08-05 23:00:00,2017-08-06 00:00:00,17.25,49.00,3.85,31.15,19.70,None,3.75,0.19,...,32.57,67.50,1.23,276.25,3.00,750.0,0.10,0.00,0.0,23.40
16,2017-08-06 11:00:00,2017-08-06 12:00:00,19.50,61.75,8.03,31.83,23.45,None,NaN,0.48,...,33.32,61.50,1.87,143.00,524.00,750.0,0.18,0.00,0.0,25.80
17,2017-08-06 21:00:00,2017-08-06 22:00:00,47.50,94.50,19.00,59.77,47.22,None,5.35,0.82,...,32.65,67.25,0.40,213.50,3.00,750.0,0.00,0.33,0.0,23.93
18,2017-08-17 15:00:00,2017-08-17 16:00:00,25.00,61.25,24.72,91.77,68.88,None,140.23,0.44,...,33.50,71.25,1.17,255.00,45.25,750.0,0.08,0.00,0.0,23.75
19,2017-08-18 06:00:00,2017-08-18 07:00:00,13.00,47.50,8.48,54.98,36.15,None,4.02,0.25,...,32.72,86.25,1.80,256.00,3.00,750.0,0.20,0.00,0.0,19.97
20,2017-08-18 19:00:00,2017-08-18 20:00:00,16.75,81.00,17.15,87.67,60.55,None,1.90,0.40,...,32.30,78.75,0.85,267.50,3.00,750.0,0.00,0.00,0.0,21.80
21,2017-08-19 01:00:00,2017-08-19 02:00:00,14.25,53.25,3.62,51.80,30.50,None,4.55,0.28,...,32.30,79.75,2.07,173.75,3.00,750.0,0.10,0.00,0.0,21.25
22,2017-08-21 03:00:00,2017-08-21 04:00:00,6.00,22.00,4.70,54.72,32.90,None,0.43,0.23,...,32.57,83.00,1.40,229.75,3.00,750.0,0.10,0.00,0.0,20.25
23,2017-08-21 04:00:00,2017-08-21 05:00:00,5.50,21.00,3.75,49.80,29.53,None,2.00,0.19,...,32.18,83.00,1.30,253.00,3.00,750.0,0.10,0.00,0.0,20.20

# NOT IN

Check whether a value is not part of a sequence.

In [ ]:
#By using Pandas
m=df[~df['BP (mmHg)'].isin([700,750,800])]
print(m)

                 From Date              To Date  PM2.5 (ug/m3)  PM10 (ug/m3)  \
0      2016-07-01 10:00:00  2016-07-01 11:00:00          10.67         39.00
1      2016-07-01 11:00:00  2016-07-01 12:00:00           2.00         39.00
2      2016-07-01 12:00:00  2016-07-01 13:00:00            NaN           NaN
3      2016-07-01 13:00:00  2016-07-01 14:00:00            NaN           NaN
4      2016-07-01 14:00:00  2016-07-01 15:00:00          20.50         50.00
...                    ...                  ...            ...           ...
30546  2019-12-26 04:00:00  2019-12-26 05:00:00          31.00         54.50
30547  2019-12-26 05:00:00  2019-12-26 06:00:00          15.00         46.25
30548  2019-12-26 06:00:00  2019-12-26 07:00:00          21.00         38.50
30549  2019-12-26 07:00:00  2019-12-26 08:00:00          22.50         51.00
30550  2019-12-26 08:00:00  2019-12-26 09:00:00          25.00         53.50

       NO (ug/m3)  NO2 (ug/m3)  NOx (ppb)  NH3 (ug/m3)  SO2 (ug/m3)  \
0           17.67        39.20      32.33         7.07         6.60
1           20.50        41.90      35.80         7.40          NaN
2             NaN          NaN        NaN          NaN          NaN
3             NaN          NaN        NaN          NaN          NaN
4           15.40        43.60      32.78         6.35         6.38
...           ...          ...        ...          ...          ...
30546       22.60        24.40      31.35        19.30         3.60
30547       13.27        19.55      21.18        17.00         2.77
30548       27.55        27.40      37.00        18.48         3.55
30549       31.38        31.13      42.07        18.90         4.67
30550       23.45        22.85      31.25        18.02         3.77

       CO (mg/m3)  ...  Temp (degree C)  RH (%)  WS (m/s)  WD (deg)  \
0            0.48  ...            33.43   71.67      2.30    226.33
1            0.49  ...            33.70   70.00      2.50    223.00
2             NaN  ...              NaN     NaN       NaN       NaN
3             NaN  ...              NaN     NaN       NaN       NaN
4            0.47  ...            33.57   63.50      1.88    223.00
...           ...  ...              ...     ...       ...       ...
30546        0.41  ...            28.52   88.00      0.55     63.50
30547        0.28  ...            28.50   78.75      0.80    108.00
30548        0.41  ...            28.55   83.50      0.52     19.00
30549        0.45  ...            28.45   86.50      0.65     73.25
30550        0.00  ...              NaN     NaN       NaN       NaN

       SR (W/mt2)  BP (mmHg)  VWS (m/s)  Xylene (ug/m3)  RF (mm)  \
0          123.67        NaN      -0.10            0.10      0.0
1          186.00        NaN      -0.10            0.10      0.0
2             NaN        NaN        NaN             NaN      NaN
3             NaN        NaN        NaN             NaN      NaN
4          240.50        NaN      -0.10            0.10      0.0
...           ...        ...        ...             ...      ...
30546        3.00        NaN       0.00            0.05      0.0
30547        3.00        NaN      -0.05            0.03      0.0
30548        3.00        NaN      -0.03            0.00      0.0
30549        3.00        NaN      -0.03            0.00      0.0
30550         NaN        NaN        NaN             NaN      NaN

       AT (degree C)
0              23.05
1                NaN
2                NaN
3                NaN
4                NaN
...              ...
30546          16.62
30547          17.40
30548          17.20
30549          17.30
30550            NaN

[30527 rows x 23 columns]

In [ ]:
m.shape

(30527, 23)

In [ ]:
#By using Pandasql
Query_string = """ select * from df where [BP (mmHg)] not in(700,750,800);"""
n=sqldf(Query_string, globals())
n

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2017-02-14 20:00:00,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,...,32.52,80.75,2.03,290.00,6.75,925.25,-0.03,1.00,0.00,18.40
1,2017-05-02 21:00:00,2017-05-02 22:00:00,30.25,76.00,7.73,46.02,30.75,8.25,4.35,0.43,...,NaN,74.25,0.75,112.75,7.00,950.75,0.00,0.00,0.00,23.13
2,2017-05-03 11:00:00,2017-05-03 12:00:00,29.00,74.75,6.12,39.45,25.93,6.83,NaN,0.45,...,32.60,50.25,1.47,140.25,640.50,952.50,0.03,0.00,0.00,28.40
3,2017-05-05 23:00:00,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,...,32.47,75.00,1.07,102.67,7.00,1050.00,0.00,0.00,0.00,23.60
4,2017-07-15 13:00:00,2017-07-15 14:00:00,23.00,65.00,6.70,29.90,21.30,NaN,3.40,0.61,...,33.20,66.00,2.50,252.00,61.00,744.00,0.20,0.00,0.00,23.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,2019-06-23 22:00:00,2019-06-23 23:00:00,9.75,11.50,1.30,25.70,14.75,19.12,0.85,0.19,...,34.12,89.00,0.32,124.00,14.25,741.00,-0.05,0.00,NaN,20.42
1158,2019-06-25 08:00:00,2019-06-25 09:00:00,26.00,46.50,36.45,39.08,50.40,22.40,3.38,0.48,...,26.43,71.50,1.55,171.00,300.25,855.00,0.17,0.10,NaN,28.95
1159,2019-11-27 22:00:00,2019-11-27 23:00:00,3.75,21.50,11.53,18.50,19.25,31.82,NaN,0.88,...,46.50,89.00,1.62,185.00,4.00,742.00,-0.10,0.03,0.12,19.08
1160,2019-11-27 23:00:00,2019-11-28 00:00:00,5.50,18.00,14.95,19.65,22.62,34.62,NaN,1.17,...,48.53,90.00,1.40,240.75,4.00,817.00,-0.10,0.03,0.00,18.60
1161,2019-11-28 00:00:00,2019-11-28 01:00:00,4.00,20.75,10.10,14.65,16.00,34.75,1.40,4.06,...,NaN,NaN,0.40,NaN,190.75,790.00,NaN,0.05,0.00,NaN

In [ ]:
n.shape

(1162, 23)

## Ascending Data Order

The default value is ascending order, whose Boolean value is True.

Except for that axis-wise, we do perform sorting such as 0 for index and 1 for columns.

In [ ]:
df.columns

Index(['From Date', 'To Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)',
       'NO2 (ug/m3)', 'NOx (ppb)', 'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)',
       'Ozone (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Temp (degree C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'SR (W/mt2)',
       'BP (mmHg)', 'VWS (m/s)', 'Xylene (ug/m3)', 'RF (mm)', 'AT (degree C)'],
      dtype='object')

In [ ]:
#By using Pandas
df.sort_values(by = ['Benzene (ug/m3)', 'Toluene (ug/m3)'], ascending= True)

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
991,2016-08-11 17:00:00,2016-08-11 18:00:00,NaN,NaN,NaN,NaN,0.00,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,26.28
992,2016-08-11 18:00:00,2016-08-11 19:00:00,NaN,NaN,NaN,NaN,0.00,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,25.25
993,2016-08-11 19:00:00,2016-08-11 20:00:00,NaN,NaN,NaN,NaN,0.00,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,24.90
994,2016-08-11 20:00:00,2016-08-11 21:00:00,NaN,NaN,NaN,NaN,0.00,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,24.70
995,2016-08-11 21:00:00,2016-08-11 22:00:00,NaN,NaN,NaN,NaN,0.00,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,24.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28030,2019-09-12 08:00:00,2019-09-12 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30045,2019-12-05 07:00:00,2019-12-05 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30046,2019-12-05 08:00:00,2019-12-05 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30047,2019-12-05 09:00:00,2019-12-05 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30550,2019-12-26 08:00:00,2019-12-26 09:00:00,25.0,53.5,23.45,22.85,31.25,18.02,3.77,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#By using Pandasql
query_string = """SELECT * FROM df ORDER BY "Benzene (ug/m3)", "Toluene (ug/m3)";"""
sorted_df_sql = sqldf(query_string, globals())

sorted_df_sql

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-07-02 00:00:00,2016-07-02 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-07-02 01:00:00,2016-07-02 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-07-02 02:00:00,2016-07-02 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30546,2017-04-20 16:00:00,2017-04-20 17:00:00,52.00,86.25,41.87,111.85,93.52,9.12,7.20,1.25,...,33.73,58.75,1.12,329.00,12.25,NaN,0.00,0.87,0.0,23.70
30547,2019-10-02 03:00:00,2019-10-02 04:00:00,25.75,48.00,0.98,10.32,6.27,22.07,1.75,0.33,...,29.18,89.00,0.62,105.75,3.00,NaN,0.00,12.50,0.0,20.73
30548,2019-12-23 00:00:00,2019-12-23 01:00:00,51.25,88.75,13.28,29.80,26.67,20.38,6.55,0.50,...,28.52,88.00,1.62,298.75,2.75,NaN,0.00,53.82,0.0,17.55
30549,2018-10-31 05:00:00,2018-10-31 06:00:00,41.25,72.25,8.57,34.45,25.32,14.40,10.00,0.20,...,31.00,87.00,3.12,95.75,2.00,NaN,0.08,9.15,0.0,19.37
30550,2018-06-13 17:00:00,2018-06-13 18:00:00,13.75,45.50,27.85,47.27,47.78,5.48,3.68,0.57,...,29.95,62.00,1.10,118.00,1.75,NaN,-0.03,0.20,0.0,24.35

# Descending Data Order

In [ ]:
#By using Pandas
df.sort_values(by = ['Benzene (ug/m3)', 'Toluene (ug/m3)'], ascending= False)

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
17095,2018-06-13 17:00:00,2018-06-13 18:00:00,13.75,45.50,27.85,47.27,47.78,5.48,3.68,0.57,...,29.95,62.00,1.10,118.00,1.75,NaN,-0.03,0.20,0.0,24.35
20443,2018-10-31 05:00:00,2018-10-31 06:00:00,41.25,72.25,8.57,34.45,25.32,14.40,10.00,0.20,...,31.00,87.00,3.12,95.75,2.00,NaN,0.08,9.15,0.0,19.37
30470,2019-12-23 00:00:00,2019-12-23 01:00:00,51.25,88.75,13.28,29.80,26.67,20.38,6.55,0.50,...,28.52,88.00,1.62,298.75,2.75,NaN,0.00,53.82,0.0,17.55
28505,2019-10-02 03:00:00,2019-10-02 04:00:00,25.75,48.00,0.98,10.32,6.27,22.07,1.75,0.33,...,29.18,89.00,0.62,105.75,3.00,NaN,0.00,12.50,0.0,20.73
7038,2017-04-20 16:00:00,2017-04-20 17:00:00,52.00,86.25,41.87,111.85,93.52,9.12,7.20,1.25,...,33.73,58.75,1.12,329.00,12.25,NaN,0.00,0.87,0.0,23.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28030,2019-09-12 08:00:00,2019-09-12 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30045,2019-12-05 07:00:00,2019-12-05 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30046,2019-12-05 08:00:00,2019-12-05 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30047,2019-12-05 09:00:00,2019-12-05 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30550,2019-12-26 08:00:00,2019-12-26 09:00:00,25.00,53.50,23.45,22.85,31.25,18.02,3.77,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#By using Pandasql
query_string = """SELECT * FROM df ORDER BY "Benzene (ug/m3)" DESC, "Toluene (ug/m3)" DESC;"""
sqldf(query_string, globals())

,From Date,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
0,2018-06-13 17:00:00,2018-06-13 18:00:00,13.75,45.50,27.85,47.27,47.78,5.48,3.68,0.57,...,29.95,62.00,1.10,118.00,1.75,NaN,-0.03,0.20,0.0,24.35
1,2018-10-31 05:00:00,2018-10-31 06:00:00,41.25,72.25,8.57,34.45,25.32,14.40,10.00,0.20,...,31.00,87.00,3.12,95.75,2.00,NaN,0.08,9.15,0.0,19.37
2,2019-12-23 00:00:00,2019-12-23 01:00:00,51.25,88.75,13.28,29.80,26.67,20.38,6.55,0.50,...,28.52,88.00,1.62,298.75,2.75,NaN,0.00,53.82,0.0,17.55
3,2019-10-02 03:00:00,2019-10-02 04:00:00,25.75,48.00,0.98,10.32,6.27,22.07,1.75,0.33,...,29.18,89.00,0.62,105.75,3.00,NaN,0.00,12.50,0.0,20.73
4,2017-04-20 16:00:00,2017-04-20 17:00:00,52.00,86.25,41.87,111.85,93.52,9.12,7.20,1.25,...,33.73,58.75,1.12,329.00,12.25,NaN,0.00,0.87,0.0,23.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30546,2019-09-12 08:00:00,2019-09-12 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30547,2019-12-05 07:00:00,2019-12-05 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30548,2019-12-05 08:00:00,2019-12-05 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30549,2019-12-05 09:00:00,2019-12-05 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30550,2019-12-26 08:00:00,2019-12-26 09:00:00,25.00,53.50,23.45,22.85,31.25,18.02,3.77,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Aggregration

In [ ]:
#By using Pandas
df.agg({'Temp (degree C)': ['count','min', 'max', 'mean']})

       Temp (degree C)
count     27876.000000
min           7.300000
max          59.780000
mean         31.185913

In [ ]:
#By using Pandasql
Query_string = """ select count([Temp (degree C)]) as count, min([Temp (degree C)]) as min, max([Temp (degree C)]) as max, avg([Temp (degree C)]) as mean from df;"""
sqldf(Query_string, globals())

   count  min    max       mean
0  27876  7.3  59.78  31.185913

## Group by

In [ ]:
#By using Pandas
df.groupby('RH (%)')['AT (degree C)'].sum()

RH (%)
15.25     0.00
18.00     0.00
18.25     0.00
20.00     4.75
20.25     4.68
         ...
90.25    21.20
90.50    15.02
91.00    18.45
91.25    19.87
92.33    19.77
Name: AT (degree C), Length: 357, dtype: float64

## Group by  with Aggregration

In [ ]:
#By using Pandas
df.groupby('RH (%)').agg({'AT (degree C)': ['mean','min','max']})

       AT (degree C)
                mean    min    max
RH (%)
15.25            NaN    NaN    NaN
18.00            NaN    NaN    NaN
18.25            NaN    NaN    NaN
20.00           4.75   4.75   4.75
20.25           4.68   4.68   4.68
...              ...    ...    ...
90.25          21.20  21.20  21.20
90.50          15.02  15.02  15.02
91.00          18.45  18.45  18.45
91.25          19.87  19.87  19.87
92.33          19.77  19.77  19.77

[357 rows x 3 columns]

In [ ]:
df.columns

Index(['From Date', 'To Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)',
       'NO2 (ug/m3)', 'NOx (ppb)', 'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)',
       'Ozone (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Temp (degree C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'SR (W/mt2)',
       'BP (mmHg)', 'VWS (m/s)', 'Xylene (ug/m3)', 'RF (mm)', 'AT (degree C)'],
      dtype='object')

In [ ]:
#By using Pandasql
Query_string = """ SELECT "RH (%)", SUM("AT (degree C)") AS Sum_temp FROM df
                  GROUP BY "RH (%)";"""
sqldf(Query_string, globals())

     RH (%)  Sum_temp
0       NaN    851.84
1     15.25       NaN
2     18.00       NaN
3     18.25       NaN
4     20.00      4.75
..      ...       ...
353   90.25     21.20
354   90.50     15.02
355   91.00     18.45
356   91.25     19.87
357   92.33     19.77

[358 rows x 2 columns]

In [ ]:
#By using Pandasql
Query_string = """ select Reason_for_absence , avg([AT (degree C)]) as mean, min([AT (degree C)]) as min, max([AT (degree C)]) as max from df
group by [VWS (m/s)];"""
# sqldf(Query_string, globals())                        # This cant be done as the column is not categorical

### This cant be done as the column is not categorical

# **Join (Merge)**

In [ ]:
df.columns

Index(['PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)', 'NO2 (ug/m3)',
       'NOx (ppb)', 'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)',
       'Ozone (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Temp (degree C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'SR (W/mt2)',
       'BP (mmHg)', 'VWS (m/s)', 'Xylene (ug/m3)', 'RF (mm)', 'AT (degree C)'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 59150 entries, 2016-07-01 11:00:00 to 2023-04-01 00:00:00
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PM2.5 (ug/m3)    54323 non-null  float64
 1   PM10 (ug/m3)     54450 non-null  float64
 2   NO (ug/m3)       55153 non-null  float64
 3   NO2 (ug/m3)      55100 non-null  float64
 4   NOx (ppb)        55315 non-null  float64
 5   NH3 (ug/m3)      53564 non-null  float64
 6   SO2 (ug/m3)      54285 non-null  float64
 7   CO (mg/m3)       54673 non-null  float64
 8   Ozone (ug/m3)    54567 non-null  float64
 9   Benzene (ug/m3)  55213 non-null  float64
 10  Toluene (ug/m3)  55213 non-null  float64
 11  Temp (degree C)  55113 non-null  float64
 12  RH (%)           55281 non-null  float64
 13  WS (m/s)         55299 non-null  float64
 14  WD (deg)         54656 non-null  float64
 15  SR (W/mt2)       54589 non-null  float64
 16  BP (mmHg)        1201 non-null   float64
 17  VWS (m/s)        55341 non-null  float64
 18  Xylene (ug/m3)   55200 non-null  float64
 19  RF (mm)          55285 non-null  float64
 20  AT (degree C)    55087 non-null  float64
dtypes: float64(21)
memory usage: 9.9 MB

In [ ]:
import numpy as np
import pandasql as ps

In [ ]:
data1 = {
    'ID': [1, 2, 3, 4, 5],
    'PM2.5 (ug/m3)': [12.5, 15.3, np.nan, 18.7, 20.1],
    'PM10 (ug/m3)': [25.1, 30.5, 22.3, np.nan, 31.4],
    'NO (ug/m3)': [5.1, 7.2, np.nan, 6.8, 8.0],
    'NO2 (ug/m3)': [12.4, np.nan, 13.8, 14.1, 15.5]
}

df1 = pd.DataFrame(data1, columns=['ID', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)', 'NO2 (ug/m3)'])

In [ ]:
data2 = {
    'ID': [3, 4, 5, 6, 7],
    'NOx (ppb)': [50, 60, np.nan, 70, 80],
    'NH3 (ug/m3)': [1.5, 2.0, 2.5, np.nan, 3.0],
    'SO2 (ug/m3)': [0.5, 0.6, 0.7, 0.8, 0.9],
    'Temp (degree C)': [20.1, 22.4, np.nan, 24.0, 23.5]
}

df2 = pd.DataFrame(data2)

# Inner Join

In [ ]:
inner_join_df = pd.merge(df1, df2, on='ID', how='inner')
inner_join_df

,ID,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),Temp (degree C)
0,3,NaN,22.3,NaN,13.8,50.0,1.5,0.5,20.1
1,4,18.7,NaN,6.8,14.1,60.0,2.0,0.6,22.4
2,5,20.1,31.4,8.0,15.5,NaN,2.5,0.7,NaN

In [ ]:
Query_string_inner = """SELECT *
                        FROM df1 AS a
                        INNER JOIN df2 AS b
                        ON a.ID = b.ID;"""

inner_join_result = ps.sqldf(Query_string_inner, globals())
inner_join_result

,ID,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),ID,NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),Temp (degree C)
0,3,NaN,22.3,NaN,13.8,3,50.0,1.5,0.5,20.1
1,4,18.7,NaN,6.8,14.1,4,60.0,2.0,0.6,22.4
2,5,20.1,31.4,8.0,15.5,5,NaN,2.5,0.7,NaN

# Left Join

In [ ]:
left_join_df = pd.merge(df1, df2, on='ID', how='left')
left_join_df

,ID,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),Temp (degree C)
0,1,12.5,25.1,5.1,12.4,NaN,NaN,NaN,NaN
1,2,15.3,30.5,7.2,NaN,NaN,NaN,NaN,NaN
2,3,NaN,22.3,NaN,13.8,50.0,1.5,0.5,20.1
3,4,18.7,NaN,6.8,14.1,60.0,2.0,0.6,22.4
4,5,20.1,31.4,8.0,15.5,NaN,2.5,0.7,NaN

In [ ]:
Query_string_left = """SELECT *
                       FROM df1 AS a
                       LEFT JOIN df2 AS b
                       ON a.ID = b.ID;"""

ps.sqldf(Query_string_left, globals())

,ID,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),ID,NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),Temp (degree C)
0,1,12.5,25.1,5.1,12.4,NaN,NaN,NaN,NaN,NaN
1,2,15.3,30.5,7.2,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,22.3,NaN,13.8,3.0,50.0,1.5,0.5,20.1
3,4,18.7,NaN,6.8,14.1,4.0,60.0,2.0,0.6,22.4
4,5,20.1,31.4,8.0,15.5,5.0,NaN,2.5,0.7,NaN

# Right Join

In [ ]:
right_join_df = pd.merge(df1, df2, on='ID', how='right')
right_join_df

,ID,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),Temp (degree C)
0,3,NaN,22.3,NaN,13.8,50.0,1.5,0.5,20.1
1,4,18.7,NaN,6.8,14.1,60.0,2.0,0.6,22.4
2,5,20.1,31.4,8.0,15.5,NaN,2.5,0.7,NaN
3,6,NaN,NaN,NaN,NaN,70.0,NaN,0.8,24.0
4,7,NaN,NaN,NaN,NaN,80.0,3.0,0.9,23.5

# Outer Join

In [ ]:
outer_join_df = pd.merge(df1, df2, on='ID', how='outer')
outer_join_df

,ID,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),Temp (degree C)
0,1,12.5,25.1,5.1,12.4,NaN,NaN,NaN,NaN
1,2,15.3,30.5,7.2,NaN,NaN,NaN,NaN,NaN
2,3,NaN,22.3,NaN,13.8,50.0,1.5,0.5,20.1
3,4,18.7,NaN,6.8,14.1,60.0,2.0,0.6,22.4
4,5,20.1,31.4,8.0,15.5,NaN,2.5,0.7,NaN
5,6,NaN,NaN,NaN,NaN,70.0,NaN,0.8,24.0
6,7,NaN,NaN,NaN,NaN,80.0,3.0,0.9,23.5

In [ ]:
Query_string_outer = """SELECT *
                        FROM df1 AS a
                        LEFT JOIN df2 AS b
                        ON a.ID = b.ID
                        UNION
                        SELECT *
                        FROM df2 AS b
                        LEFT JOIN df1 AS a
                        ON a.ID = b.ID;"""

outer_join_result = ps.sqldf(Query_string_outer, globals())
outer_join_result

,ID,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),ID,NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),Temp (degree C)
0,1,12.5,25.1,5.1,12.4,NaN,NaN,NaN,NaN,NaN
1,2,15.3,30.5,7.2,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,22.3,NaN,13.8,3.0,50.0,1.5,0.5,20.1
3,3,50.0,1.5,0.5,20.1,3.0,NaN,22.3,NaN,13.8
4,4,18.7,NaN,6.8,14.1,4.0,60.0,2.0,0.6,22.4
5,4,60.0,2.0,0.6,22.4,4.0,18.7,NaN,6.8,14.1
6,5,NaN,2.5,0.7,NaN,5.0,20.1,31.4,8.0,15.5
7,5,20.1,31.4,8.0,15.5,5.0,NaN,2.5,0.7,NaN
8,6,70.0,NaN,0.8,24.0,NaN,NaN,NaN,NaN,NaN
9,7,80.0,3.0,0.9,23.5,NaN,NaN,NaN,NaN,NaN

# **Summary of the DataFrame**

In [ ]:
df.describe()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
count,27670.000000,27699.000000,27940.000000,27946.000000,28079.000000,26365.000000,27294.000000,27739.000000,27847.000000,28093.000000,...,27876.000000,28028.000000,28038.000000,28031.000000,27356.000000,1186.000000,28086.000000,28080.000000,28005.000000,27904.000000
mean,29.416465,63.302538,16.517329,54.354711,41.767892,12.532404,5.590926,0.527699,29.352135,0.808343,...,31.185913,70.093137,1.479660,180.720242,70.721915,755.768128,0.030164,0.236559,0.074439,21.958922
std,20.951696,32.816495,19.421461,33.212471,27.418307,6.462997,5.074892,1.143251,20.584023,1.187507,...,3.577054,13.711231,0.740406,75.350758,133.498446,14.798723,0.206513,1.418050,0.545400,3.107099
min,0.250000,3.000000,0.100000,0.800000,0.000000,0.100000,0.030000,0.000000,0.070000,0.000000,...,7.300000,15.250000,0.080000,2.750000,0.000000,725.000000,-17.600000,0.000000,0.000000,4.680000
25%,13.000000,38.750000,5.400000,29.680000,23.000000,7.800000,3.150000,0.270000,16.670000,0.400000,...,29.250000,60.250000,0.930000,125.000000,3.000000,751.750000,-0.080000,0.000000,0.000000,19.780000
50%,23.750000,59.000000,10.800000,46.580000,35.600000,11.100000,4.880000,0.390000,20.570000,0.700000,...,30.800000,71.250000,1.400000,177.250000,5.500000,755.250000,0.000000,0.080000,0.000000,21.630000
75%,42.250000,83.500000,20.620000,73.930000,53.500000,17.170000,7.030000,0.530000,36.380000,1.080000,...,32.570000,82.000000,1.920000,236.000000,62.500000,758.000000,0.100000,0.150000,0.000000,23.950000
max,449.500000,929.000000,288.170000,313.650000,364.800000,140.820000,199.770000,41.100000,188.400000,118.520000,...,59.780000,92.330000,34.850000,360.000000,956.000000,1050.000000,1.700000,81.000000,30.000000,35.350000

# **Resampling**

Resampling is a method to convert the time-based observed data into a different interval.

For instance, change monthly data into a year-wise format or upsample week data into hours.

In [ ]:
df.columns

Index(['From Date', 'To Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)',
       'NO2 (ug/m3)', 'NOx (ppb)', 'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)',
       'Ozone (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Temp (degree C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'SR (W/mt2)',
       'BP (mmHg)', 'VWS (m/s)', 'Xylene (ug/m3)', 'RF (mm)', 'AT (degree C)'],
      dtype='object')

In [ ]:
import pandas as pd
df = pd.read_csv(r'/content/Air Quality.csv',index_col =0,parse_dates=['From Date'])
df.head(5)

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.60,0.48,14.5,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.6,32.78,6.35,6.38,0.47,10.5,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.1,0.0,NaN

# Resampling by Month

In [ ]:
df['To Date'] = pd.to_datetime(df['To Date'])
df.set_index('To Date', inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 59150 entries, 2016-07-01 11:00:00 to 2023-04-01 00:00:00
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PM2.5 (ug/m3)    54323 non-null  float64
 1   PM10 (ug/m3)     54450 non-null  float64
 2   NO (ug/m3)       55153 non-null  float64
 3   NO2 (ug/m3)      55100 non-null  float64
 4   NOx (ppb)        55315 non-null  float64
 5   NH3 (ug/m3)      53564 non-null  float64
 6   SO2 (ug/m3)      54285 non-null  float64
 7   CO (mg/m3)       54673 non-null  float64
 8   Ozone (ug/m3)    54567 non-null  float64
 9   Benzene (ug/m3)  55213 non-null  float64
 10  Toluene (ug/m3)  55213 non-null  float64
 11  Temp (degree C)  55113 non-null  float64
 12  RH (%)           55281 non-null  float64
 13  WS (m/s)         55299 non-null  float64
 14  WD (deg)         54656 non-null  float64
 15  SR (W/mt2)       54589 non-null  float64
 16  BP (mmHg)        1201 non-null   float64
 17  VWS (m/s)        55341 non-null  float64
 18  Xylene (ug/m3)   55200 non-null  float64
 19  RF (mm)          55285 non-null  float64
 20  AT (degree C)    55087 non-null  float64
dtypes: float64(21)
memory usage: 9.9 MB

In [ ]:
 df.resample('M').mean()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-31,13.609968,38.735399,17.385351,43.581629,34.159217,8.091461,5.091833,0.845176,14.302995,0.708626,...,32.825240,70.660911,1.609153,163.401981,115.709217,NaN,0.136278,0.192875,0.511677,23.062740
2016-08-31,11.984526,44.502779,19.584459,46.320549,36.113379,7.922332,5.011009,0.792736,17.702341,0.653783,...,32.938354,65.777876,1.501702,290.870675,119.050999,NaN,0.142189,0.238289,0.119562,23.586174
2016-09-30,15.848221,38.808325,18.711123,48.708117,37.504182,8.925594,5.154018,0.837194,16.707448,0.759759,...,33.373022,70.549119,1.437340,226.558480,98.144458,NaN,0.261084,0.245594,0.157814,22.842874
2016-10-31,41.471343,81.426575,26.109213,86.125815,62.507628,13.735321,7.051236,0.894543,15.542489,1.585545,...,33.261050,61.207873,1.346906,202.652680,111.994538,NaN,0.208910,2.405034,0.072317,23.174138
2016-11-30,56.789811,88.870102,22.785936,103.111814,72.896556,10.120559,6.752576,0.931621,17.630827,1.640174,...,33.104224,68.911001,2.058345,249.530392,106.467077,NaN,-0.077800,1.367771,0.091491,20.625326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31,48.720488,69.526459,16.037970,37.160497,32.805780,6.164059,7.084541,0.923468,29.896121,1.728616,...,30.448091,80.636425,1.024624,141.863929,61.846438,NaN,-0.110618,0.665699,0.085739,21.173535
2023-01-31,53.020946,75.954392,17.579420,44.203482,37.780567,5.991903,5.956909,0.870634,20.056788,2.052551,...,30.569744,76.367072,0.905263,191.286705,90.558704,NaN,-0.142213,0.791754,0.002699,20.542470
2023-02-28,49.656994,79.990313,16.566503,50.934821,40.561131,5.812039,10.125529,0.834182,22.443244,1.591071,...,30.401607,58.102798,0.723958,175.428701,110.898185,NaN,-0.165580,1.278929,0.000179,22.768690
2023-03-31,35.998664,57.107503,11.566181,46.623915,34.204821,6.813319,6.128008,0.859650,13.060165,0.998748,...,30.453365,67.860700,0.614616,143.981640,104.868775,NaN,-0.160915,0.701602,0.021561,23.621817
2023-04-30,26.000000,53.000000,3.330000,24.070000,15.500000,7.700000,1.830000,0.810000,8.370000,1.000000,...,30.670000,87.000000,0.330000,NaN,11.000000,NaN,-0.130000,0.830000,0.000000,23.500000

# Resampling by Quarter

In [ ]:
df.resample('Q').mean()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-09-30,13.686726,40.893861,18.602046,46.147187,35.899112,8.279335,5.080538,0.823003,16.294129,0.703577,...,33.032751,68.815104,1.517359,229.789170,111.703911,NaN,0.175924,0.225732,0.257688,23.168049
2016-12-31,49.472509,83.710610,24.967318,95.452935,69.160910,11.161877,6.428447,0.923957,16.869915,1.604540,...,33.016680,68.021126,1.801609,213.398815,103.296326,NaN,0.023046,1.460428,0.199903,21.098297
2017-03-31,39.880901,72.317810,19.188776,102.328566,69.967484,8.709559,5.463502,0.894911,16.278879,1.274388,...,33.688897,64.867781,1.505558,222.368239,112.906214,925.250000,-0.044706,0.312474,0.036662,21.101798
2017-06-30,28.715615,65.963740,6.567646,49.542160,31.559367,5.660645,5.633863,0.660268,17.025759,0.974871,...,35.736507,60.047856,1.419206,188.272888,124.580167,984.416667,0.046036,0.161193,0.096625,25.346784
2017-09-30,18.091745,45.057744,12.970645,64.290839,44.619551,7.723256,4.873116,0.366336,23.256461,0.132505,...,32.749309,75.485296,1.326401,176.933527,48.371930,754.734215,0.068367,0.020415,0.097878,22.342870
2017-12-31,40.208397,69.450276,23.416609,73.264943,55.508443,11.675962,5.214003,0.284991,32.073621,0.664224,...,32.321997,80.074546,1.857961,123.879537,37.941268,NaN,-0.028878,0.135000,0.061089,19.936269
2018-03-31,45.637415,81.822675,24.093490,71.941248,57.811292,12.884444,6.339806,0.528005,38.472812,0.920225,...,30.620039,63.223420,1.429004,153.181178,68.343139,NaN,-0.029103,0.130381,0.006479,20.470309
2018-06-30,21.698908,71.605126,13.627369,37.438216,30.964532,9.710468,4.377393,0.451627,24.295090,0.878978,...,29.452357,68.758455,1.297030,181.385262,70.590845,NaN,0.073301,0.069606,0.018885,23.726494
2018-09-30,12.223015,49.396734,14.296045,28.585259,26.831575,6.007292,6.638777,0.401585,15.261232,0.615948,...,30.004902,69.790163,1.665953,165.293927,45.870817,NaN,0.130855,0.123415,0.074395,22.594641
2018-12-31,38.369185,77.775332,15.317466,46.104433,36.953970,11.772400,9.274809,0.358612,49.363151,0.960743,...,30.639049,77.815218,1.759844,159.432359,42.117576,834.666667,-0.041070,0.144261,0.116962,20.017472
2019-03-31,39.064409,78.834385,12.005636,50.612554,36.661320,14.728766,7.338589,0.365209,57.819514,0.862941,...,29.710258,67.954215,1.310834,158.897302,59.970142,740.000000,-0.020698,0.105162,0.002253,20.672895
2019-06-30,19.619746,60.695024,10.811182,41.662943,30.918791,23.530548,4.611425,0.396731,50.366208,0.592173,...,28.964705,59.785744,1.158162,178.684346,103.180896,773.666667,0.059849,0.139877,0.006190,25.194596
2019-09-30,14.243418,33.163424,16.009683,25.023975,26.323286,18.195767,2.116823,0.346190,21.812415,0.350625,...,28.890188,73.084375,1.287537,170.085974,42.025644,NaN,0.105616,0.081448,0.024669,22.590859
2019-12-31,22.506768,49.970336,17.942047,26.124795,28.479430,18.363101,4.419097,0.565729,24.213981,0.600692,...,28.550462,83.609826,1.318570,214.922869,29.507897,783.000000,-0.052356,0.129054,0.056327,20.034458
2020-03-31,30.031466,54.805392,15.917319,27.692091,27.418751,13.202233,5.863745,0.465450,31.565459,0.428868,...,28.875525,72.021576,1.004873,168.372275,58.357504,743.000000,-0.042800,0.149936,0.002085,20.475408
2020-06-30,16.857422,39.813621,2.624461,7.843000,6.260687,4.583829,4.914821,0.453505,43.937647,0.294855,...,28.398480,66.739641,0.776039,165.030018,69.354565,732.000000,0.036863,0.110388,0.011105,24.029562
2020-09-30,14.406913,29.097654,3.835564,8.970689,7.867535,3.943679,5.253348,0.647277,26.734959,0.522129,...,28.809615,78.438074,0.882451,167.555027,40.291876,736.000000,0.034336,0.171530,0.055918,21.926851
2020-12-31,36.023433,55.194773,6.277565,24.937251,18.368714,8.656343,6.099923,0.844651,39.437488,1.240764,...,28.572903,81.559977,1.368264,232.370014,32.715207,NaN,-0.040118,0.329736,0.070954,19.893694
2021-03-31,43.506670,70.707215,15.284852,41.210385,34.333149,9.531303,7.632785,0.832129,35.577548,1.645715,...,28.097327,67.680164,0.993055,231.039905,59.570607,NaN,-0.054570,0.670377,0.005070,20.400547
2021-06-30,21.782521,54.856947,4.787353,16.243930,12.501525,8.557523,5.939830,0.544540,35.035277,0.624717,...,28.558563,68.874869,0.777891,156.688134,100.131109,NaN,-0.049306,0.196901,0.018104,25.012896
2021-09-30,12.477486,31.110100,8.549135,18.635343,16.862521,7.050118,4.577786,0.735218,18.186392,0.543294,...,29.200592,76.009817,0.545066,150.669713,96.566809,757.250000,-0.076875,0.327936,0.038257,24.113111
2021-12-31,35.766815,50.553967,7.200204,18.323710,15.411462,6.268695,5.280877,0.879093,26.147350,0.845551,...,30.082812,83.190370,0.983723,199.041149,63.468011,NaN,-0.069043,0.556353,0.080967,22.063076
2022-03-31,44.229042,73.220982,4.535593,22.384068,15.303081,8.282474,7.280854,0.857194,32.758246,0.544244,...,29.756974,71.250039,0.748967,192.222844,97.530362,NaN,-0.092640,0.178553,0.004158,22.544398
2022-06-30,30.344606,66.636382,9.647535,25.005028,21.144600,9.029959,6.266753,0.869953,22.520754,0.314325,...,30.341526,69.313655,0.473227,156.742661,113.179686,750.625000,-0.087428,0.176119,0.003222,25.751990
2022-09-30,18.144201,40.162890,14.084000,18.714082,21.388850,7.438434,4.685313,0.796164,10.829598,0.484097,...,30.533966,75.808785,0.806435,160.777537,86.301921,NaN,-0.114657,0.528634,0.035978,24.261420
2022-12-31,41.001005,62.305875,15.526628,29.637448,28.368498,6.401523,6.740505,0.928019,23.260961,1.587985,...,30.546471,80.394024,0.877246,171.667298,67.084284,NaN,-0.118360,0.877647,0.053019,21.988235
2023-03-31,46.112406,70.723239,15.216824,47.139276,37.437454,6.211662,7.330536,0.855487,18.426782,1.545552,...,30.477231,67.742848,0.748590,170.263536,101.829814,NaN,-0.155942,0.912532,0.008414,22.297560
2023-06-30,26.000000,53.000000,3.330000,24.070000,15.500000,7.700000,1.830000,0.810000,8.370000,1.000000,...,30.670000,87.000000,0.330000,NaN,11.000000,NaN,-0.130000,0.830000,0.000000,23.500000

# Resampling by Year

In [ ]:
df.resample('Y').mean()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-12-31,32.198483,63.031514,21.892990,71.639017,53.017318,9.773848,5.777671,0.874922,16.589525,1.168656,...,33.024442,68.404605,1.664321,221.317100,107.376942,NaN,0.097245,0.863085,0.227949,22.068710
2017-12-31,32.974509,64.654892,15.905196,73.548099,51.327091,8.727996,5.326381,0.563006,22.232347,0.808629,...,33.613638,69.947079,1.548557,177.418928,82.454701,755.465136,0.004298,0.168440,0.070153,22.074179
2018-12-31,30.570605,70.669209,16.995163,46.800424,38.688775,10.245874,6.811522,0.433731,32.923316,0.850774,...,30.218478,70.080033,1.547418,164.111150,56.243142,834.666667,0.028176,0.118995,0.056012,21.575671
2019-12-31,23.781936,55.373353,14.237229,35.703364,30.551262,18.698963,4.624098,0.414641,38.318862,0.600428,...,29.025544,71.217059,1.269448,180.816263,54.359797,772.857143,0.022937,0.113787,0.022699,22.106403
2020-12-31,24.374958,44.619942,7.106807,17.278387,14.903186,7.564955,5.532970,0.604246,35.383447,0.626558,...,28.663471,74.740914,1.008643,183.470638,50.018232,737.000000,-0.002725,0.191469,0.035366,21.581946
2021-12-31,28.619476,51.792076,9.123126,23.869339,20.072709,7.825967,5.854018,0.756324,28.460770,0.927246,...,29.003871,74.153623,0.827609,185.605323,79.105751,757.250000,-0.062940,0.447847,0.036312,22.835842
2022-12-31,33.169356,60.334745,10.921011,23.799460,21.451885,7.791197,6.238225,0.860963,22.251019,0.723531,...,30.293077,74.171331,0.727977,170.307158,91.070607,750.625000,-0.103325,0.437693,0.024010,23.638843
2023-12-31,46.103069,70.715007,15.211275,47.128506,37.427213,6.212360,7.327951,0.855466,18.422087,1.545299,...,30.477320,67.751776,0.748396,170.263536,101.787705,NaN,-0.155930,0.912494,0.008410,22.298118

# Resampling by Week

In [ ]:
df.resample('W').mean()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-03,16.138200,53.721800,17.070200,42.257600,33.307200,8.149388,5.507234,0.793000,13.517959,0.715800,...,33.090600,66.473400,1.833600,213.703600,116.245200,NaN,-0.051400,0.186000,0.090800,24.309792
2016-07-10,11.159503,36.259876,13.233789,37.216460,27.962981,6.296943,5.038645,0.722174,14.375901,0.529627,...,32.482360,69.387143,2.080373,218.674534,97.097205,NaN,0.059193,0.124410,0.205342,23.113665
2016-07-17,16.081394,43.992485,17.183758,42.762909,33.603636,8.657625,5.329810,0.721091,13.712622,0.781091,...,32.988424,66.673758,1.551091,223.554121,140.827152,NaN,0.183152,0.211697,0.260667,23.954364
2016-07-24,12.359897,36.189691,21.414536,47.035567,38.842165,9.262766,4.753548,0.908969,15.072887,0.639794,...,32.963608,71.535979,1.457216,152.168454,95.648557,NaN,0.123711,0.212990,0.460412,22.367835
2016-07-31,13.489608,32.387386,19.519935,49.405490,38.588105,8.616376,4.973333,1.085033,14.628800,0.860131,...,32.835621,77.114837,1.198889,31.052876,120.749477,NaN,0.236144,0.234118,1.274771,22.096928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-05,40.226190,64.411677,13.183155,66.063095,45.858690,5.829755,6.999461,0.813452,21.880714,0.977500,...,30.361429,54.613095,0.765298,185.076797,114.050595,NaN,-0.168155,0.687560,0.000714,22.872857
2023-03-12,37.754464,62.480655,15.649226,56.919107,43.000000,5.278765,6.416131,0.811012,13.458214,1.260952,...,30.383988,59.052083,0.752738,174.134303,112.974702,NaN,-0.158333,0.666964,0.000000,22.775238
2023-03-19,36.425210,55.044371,15.156250,43.463487,35.441776,6.300329,4.936013,0.928563,10.483421,1.201078,...,30.229521,71.089820,0.558743,138.720968,90.955090,NaN,-0.145749,0.675509,0.086886,23.239222
2023-03-26,25.504491,41.983533,6.957560,29.766310,21.492202,8.409821,5.044311,0.855536,10.607798,0.526131,...,30.639048,77.714286,0.457440,103.408354,100.747024,NaN,-0.170000,0.615952,0.008988,24.297381
2023-04-02,41.547917,62.987500,7.173554,35.309669,24.617190,8.264050,7.620661,0.893884,11.707686,1.026612,...,30.699091,75.557851,0.507355,126.057500,108.838843,NaN,-0.170083,0.936198,0.000000,25.009752

# Resampling on a Semimonthly Basis

In [ ]:
df.resample('SM').mean()

date
1958-12-31    37.642857
1959-01-15    41.375000
1959-01-31    38.533333
1959-02-15    43.384615
1959-02-28    38.000000
1959-03-15    39.812500
1959-03-31    38.333333
1959-04-15    40.666667
1959-04-30    39.133333
1959-05-15    39.625000
1959-05-31    40.800000
1959-06-15    38.600000
1959-06-30    43.733333
1959-07-15    41.375000
1959-07-31    43.733333
1959-08-15    43.250000
1959-08-31    45.333333
1959-09-15    50.266667
1959-09-30    47.800000
1959-10-15    41.312500
1959-10-31    44.466667
1959-11-15    45.133333
1959-11-30    40.933333
1959-12-15    43.875000
1959-12-31    50.000000
Freq: SM-15, Name: births, dtype: float64

## **Windowing Function**

#Rolling Window

The rolling window feature supports the following methods: count, sum,
mean, median, var, std, min, max, corr, cov, skew, kurt, quantile, sum, and
aggregate

In [ ]:
df.rolling(window=4).mean().head(5)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Expanding Window

Expanding window supports the following methods: count, sum, mean,
median, var, std, min, max, corr, cov, skew, kurt, quantile, sum, aggregate,
and quantile.

In [ ]:
df.expanding(min_periods=5).mean().head(5)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Exponentially Weighted Moving Window

Expanding window supports the following methods: mean, std, var, corr, and cov.

![image.png]()

In [ ]:
df.ewm(com=0.5).mean().head(5)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,10.670000,39.000000,17.670000,39.200000,32.330000,7.070000,6.600000,0.480000,14.500000,1.000000,...,33.430000,71.670000,2.300000,226.330000,123.6700,NaN,-0.1,0.1,0.0,23.05
2016-07-01 12:00:00,4.167500,39.000000,19.792500,41.225000,34.932500,7.317500,6.600000,0.487500,14.875000,0.775000,...,33.632500,70.417500,2.450000,223.832500,170.4175,NaN,-0.1,0.1,0.0,23.05
2016-07-01 13:00:00,4.167500,39.000000,19.792500,41.225000,34.932500,7.317500,6.600000,0.487500,14.875000,0.775000,...,33.632500,70.417500,2.450000,223.832500,170.4175,NaN,-0.1,0.1,0.0,23.05
2016-07-01 14:00:00,4.167500,39.000000,19.792500,41.225000,34.932500,7.317500,6.600000,0.487500,14.875000,0.775000,...,33.632500,70.417500,2.450000,223.832500,170.4175,NaN,-0.1,0.1,0.0,23.05
2016-07-01 15:00:00,19.731412,49.482353,15.606706,43.488235,32.881294,6.395529,6.382683,0.470824,10.705882,0.608235,...,33.572941,63.825529,1.906824,223.039176,237.2020,NaN,-0.1,0.1,0.0,23.05

# **Shifting**

Shifting is also known as “lag” and moves a value back or forward in time.

Shift an index by the desired number of periods with an optional time frequency.

In [ ]:
df.shift(periods=3).head(7) #it shifts the data downward (or forward) by the specified number of periods.

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.6,0.48,14.5,1.0,...,33.43,71.67,2.3,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 15:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,0.7,...,33.70,70.00,2.5,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shift(periods=-1).head(7) #it shifts the data upward (or backward) by the specified number of periods.

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,2.00,39.0,20.50,41.90,35.80,7.40,NaN,0.49,15.00,0.70,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.10,0.0,NaN
2016-07-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,20.50,50.0,15.40,43.60,32.78,6.35,6.38,0.47,10.50,0.60,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.10,0.0,NaN
2016-07-01 15:00:00,15.25,59.5,24.30,45.12,40.12,6.65,6.53,0.51,6.60,0.77,...,33.55,63.75,1.40,213.25,152.25,NaN,-0.1,0.10,0.0,25.60
2016-07-01 16:00:00,11.67,60.0,26.73,49.10,43.80,6.93,5.70,0.46,17.43,0.80,...,33.57,64.00,1.50,208.67,92.67,NaN,-0.1,0.23,0.0,25.70
2016-07-01 17:00:00,11.75,57.5,19.10,46.33,36.82,8.12,6.23,0.44,19.98,0.70,...,33.48,64.00,1.95,222.75,35.00,NaN,-0.1,0.10,0.0,25.15

##shifting the data along the columns, rather than the rows. This means that the values in each column will be shifted horizontally rather than vertically.

In [ ]:
df.shift(periods=3, axis =1).head(7)

,ISE,ISED,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
date,,,,,,,,,
2009-01-05,NaN,NaN,NaN,0.035754,0.038376,-0.004679,0.002193,0.003894,0.000000
2009-01-06,NaN,NaN,NaN,0.025426,0.031813,0.007787,0.008455,0.012866,0.004162
2009-01-07,NaN,NaN,NaN,-0.028862,-0.026353,-0.030469,-0.017833,-0.028735,0.017293
2009-01-08,NaN,NaN,NaN,-0.062208,-0.084716,0.003391,-0.011726,-0.000466,-0.040061
2009-01-09,NaN,NaN,NaN,0.009860,0.009658,-0.021533,-0.019873,-0.012710,-0.004474
2009-01-12,NaN,NaN,NaN,-0.029191,-0.042361,-0.022823,-0.013526,-0.005026,-0.049039
2009-01-13,NaN,NaN,NaN,0.015445,-0.000272,0.001757,-0.017674,-0.006141,0.000000

In [ ]:
df.shift(periods=3,fill_value=0).head(7)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00
2016-07-01 12:00:00,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00
2016-07-01 13:00:00,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00
2016-07-01 14:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.6,0.48,14.5,1.0,...,33.43,71.67,2.3,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 15:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,0.7,...,33.70,70.00,2.5,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shift(periods=3,fill_value=0,axis =1).head(7)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,0.0,0.0,0.0,10.67,39.0,17.67,39.20,32.33,7.07,6.60,...,14.50,1.00,4.63,33.43,71.67,2.30,226.33,123.67,NaN,-0.1
2016-07-01 12:00:00,0.0,0.0,0.0,2.00,39.0,20.50,41.90,35.80,7.40,NaN,...,15.00,0.70,4.50,33.70,70.00,2.50,223.00,186.00,NaN,-0.1
2016-07-01 13:00:00,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 15:00:00,0.0,0.0,0.0,20.50,50.0,15.40,43.60,32.78,6.35,6.38,...,10.50,0.60,4.50,33.57,63.50,1.88,223.00,240.50,NaN,-0.1
2016-07-01 16:00:00,0.0,0.0,0.0,15.25,59.5,24.30,45.12,40.12,6.65,6.53,...,6.60,0.77,5.33,33.55,63.75,1.40,213.25,152.25,NaN,-0.1
2016-07-01 17:00:00,0.0,0.0,0.0,11.67,60.0,26.73,49.10,43.80,6.93,5.70,...,17.43,0.80,6.47,33.57,64.00,1.50,208.67,92.67,NaN,-0.1

# **Handling missing data**

# isNull

In [ ]:
# Snippet to check for nulls
df.isnull().sum()

PM2.5 (ug/m3)       4827
PM10 (ug/m3)        4700
NO (ug/m3)          3997
NO2 (ug/m3)         4050
NOx (ppb)           3835
NH3 (ug/m3)         5586
SO2 (ug/m3)         4865
CO (mg/m3)          4477
Ozone (ug/m3)       4583
Benzene (ug/m3)     3937
Toluene (ug/m3)     3937
Temp (degree C)     4037
RH (%)              3869
WS (m/s)            3851
WD (deg)            4494
SR (W/mt2)          4561
BP (mmHg)          57949
VWS (m/s)           3809
Xylene (ug/m3)      3950
RF (mm)             3865
AT (degree C)       4063
dtype: int64

# BFill

###Backward fill involves filling missing values with the next known value that follows them. This method assumes that the next observed value is the best estimate for the missing values.

In [ ]:
df.bfill()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,10.67,39.00,17.67,39.20,32.33,7.07,6.60,0.48,14.50,1.00,...,33.43,71.67,2.30,226.33,123.67,925.25,-0.10,0.10,0.0,23.05
2016-07-01 12:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.38,0.49,15.00,0.70,...,33.70,70.00,2.50,223.00,186.00,925.25,-0.10,0.10,0.0,25.60
2016-07-01 13:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,0.60,...,33.57,63.50,1.88,223.00,240.50,925.25,-0.10,0.10,0.0,25.60
2016-07-01 14:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,0.60,...,33.57,63.50,1.88,223.00,240.50,925.25,-0.10,0.10,0.0,25.60
2016-07-01 15:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,0.60,...,33.57,63.50,1.88,223.00,240.50,925.25,-0.10,0.10,0.0,25.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 20:00:00,53.00,70.25,11.03,61.15,41.52,8.30,3.68,1.16,12.30,1.55,...,30.57,72.75,0.45,310.00,10.75,NaN,-0.20,0.85,0.0,25.23
2023-03-31 21:00:00,58.50,88.50,9.22,52.23,35.27,7.45,3.02,1.07,11.17,2.35,...,30.65,78.50,0.35,37.00,11.00,NaN,-0.20,1.05,0.0,24.62
2023-03-31 22:00:00,44.25,80.50,3.40,34.95,21.35,7.25,1.62,0.85,10.60,1.72,...,30.68,82.50,0.35,37.00,11.00,NaN,-0.20,0.73,0.0,24.23
2023-03-31 23:00:00,31.25,59.00,3.45,27.48,17.40,7.50,1.82,0.83,9.00,1.50,...,30.60,86.00,0.30,NaN,11.00,NaN,-0.15,0.88,0.0,23.82
2023-04-01 00:00:00,26.00,53.00,3.33,24.07,15.50,7.70,1.83,0.81,8.37,1.00,...,30.67,87.00,0.33,NaN,11.00,NaN,-0.13,0.83,0.0,23.50

# FFill

###Forward fill involves filling missing values with the last known value that precedes them. This method assumes that the last observed value is the best estimate for the missing values.

In [ ]:
df.ffill()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,10.67,39.00,17.67,39.20,32.33,7.07,6.60,0.48,14.50,1.00,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.10,0.10,0.0,23.05
2016-07-01 12:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.60,0.49,15.00,0.70,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.10,0.10,0.0,23.05
2016-07-01 13:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.60,0.49,15.00,0.70,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.10,0.10,0.0,23.05
2016-07-01 14:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.60,0.49,15.00,0.70,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.10,0.10,0.0,23.05
2016-07-01 15:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,0.60,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.10,0.10,0.0,23.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 20:00:00,53.00,70.25,11.03,61.15,41.52,8.30,3.68,1.16,12.30,1.55,...,30.57,72.75,0.45,310.00,10.75,749.0,-0.20,0.85,0.0,25.23
2023-03-31 21:00:00,58.50,88.50,9.22,52.23,35.27,7.45,3.02,1.07,11.17,2.35,...,30.65,78.50,0.35,310.00,11.00,749.0,-0.20,1.05,0.0,24.62
2023-03-31 22:00:00,44.25,80.50,3.40,34.95,21.35,7.25,1.62,0.85,10.60,1.72,...,30.68,82.50,0.35,37.00,11.00,749.0,-0.20,0.73,0.0,24.23
2023-03-31 23:00:00,31.25,59.00,3.45,27.48,17.40,7.50,1.82,0.83,9.00,1.50,...,30.60,86.00,0.30,37.00,11.00,749.0,-0.15,0.88,0.0,23.82
2023-04-01 00:00:00,26.00,53.00,3.33,24.07,15.50,7.70,1.83,0.81,8.37,1.00,...,30.67,87.00,0.33,37.00,11.00,749.0,-0.13,0.83,0.0,23.50

# FillNA

In [ ]:
df.fillna(10)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,10.67,39.00,17.67,39.20,32.33,7.07,6.60,0.48,14.50,1.00,...,33.43,71.67,2.30,226.33,123.67,10.0,-0.10,0.10,0.0,23.05
2016-07-01 12:00:00,2.00,39.00,20.50,41.90,35.80,7.40,10.00,0.49,15.00,0.70,...,33.70,70.00,2.50,223.00,186.00,10.0,-0.10,0.10,0.0,10.00
2016-07-01 13:00:00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,...,10.00,10.00,10.00,10.00,10.00,10.0,10.00,10.00,10.0,10.00
2016-07-01 14:00:00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,...,10.00,10.00,10.00,10.00,10.00,10.0,10.00,10.00,10.0,10.00
2016-07-01 15:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,0.60,...,33.57,63.50,1.88,223.00,240.50,10.0,-0.10,0.10,0.0,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 20:00:00,53.00,70.25,11.03,61.15,41.52,8.30,3.68,1.16,12.30,1.55,...,30.57,72.75,0.45,310.00,10.75,10.0,-0.20,0.85,0.0,25.23
2023-03-31 21:00:00,58.50,88.50,9.22,52.23,35.27,7.45,3.02,1.07,11.17,2.35,...,30.65,78.50,0.35,10.00,11.00,10.0,-0.20,1.05,0.0,24.62
2023-03-31 22:00:00,44.25,80.50,3.40,34.95,21.35,7.25,1.62,0.85,10.60,1.72,...,30.68,82.50,0.35,37.00,11.00,10.0,-0.20,0.73,0.0,24.23
2023-03-31 23:00:00,31.25,59.00,3.45,27.48,17.40,7.50,1.82,0.83,9.00,1.50,...,30.60,86.00,0.30,10.00,11.00,10.0,-0.15,0.88,0.0,23.82
2023-04-01 00:00:00,26.00,53.00,3.33,24.07,15.50,7.70,1.83,0.81,8.37,1.00,...,30.67,87.00,0.33,10.00,11.00,10.0,-0.13,0.83,0.0,23.50

# Interpolate

Fills in missing data by calculating the intermediate values based on the linear trend of surrounding data points

In [ ]:
df.interpolate(method='linear',limit_direction='forward')

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
To Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 11:00:00,10.670000,39.000000,17.67,39.200000,32.330000,7.07,6.600,0.480000,14.50,1.000000,...,33.430000,71.670000,2.300000,226.33,123.670000,NaN,-0.10,0.10,0.0,23.05
2016-07-01 12:00:00,2.000000,39.000000,20.50,41.900000,35.800000,7.40,6.545,0.490000,15.00,0.700000,...,33.700000,70.000000,2.500000,223.00,186.000000,NaN,-0.10,0.10,0.0,23.56
2016-07-01 13:00:00,8.166667,42.666667,18.80,42.466667,34.793333,7.05,6.490,0.483333,13.50,0.666667,...,33.656667,67.833333,2.293333,223.00,204.166667,NaN,-0.10,0.10,0.0,24.07
2016-07-01 14:00:00,14.333333,46.333333,17.10,43.033333,33.786667,6.70,6.435,0.476667,12.00,0.633333,...,33.613333,65.666667,2.086667,223.00,222.333333,NaN,-0.10,0.10,0.0,24.58
2016-07-01 15:00:00,20.500000,50.000000,15.40,43.600000,32.780000,6.35,6.380,0.470000,10.50,0.600000,...,33.570000,63.500000,1.880000,223.00,240.500000,NaN,-0.10,0.10,0.0,25.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 20:00:00,53.000000,70.250000,11.03,61.150000,41.520000,8.30,3.680,1.160000,12.30,1.550000,...,30.570000,72.750000,0.450000,310.00,10.750000,749.0,-0.20,0.85,0.0,25.23
2023-03-31 21:00:00,58.500000,88.500000,9.22,52.230000,35.270000,7.45,3.020,1.070000,11.17,2.350000,...,30.650000,78.500000,0.350000,173.50,11.000000,749.0,-0.20,1.05,0.0,24.62
2023-03-31 22:00:00,44.250000,80.500000,3.40,34.950000,21.350000,7.25,1.620,0.850000,10.60,1.720000,...,30.680000,82.500000,0.350000,37.00,11.000000,749.0,-0.20,0.73,0.0,24.23
2023-03-31 23:00:00,31.250000,59.000000,3.45,27.480000,17.400000,7.50,1.820,0.830000,9.00,1.500000,...,30.600000,86.000000,0.300000,37.00,11.000000,749.0,-0.15,0.88,0.0,23.82
2023-04-01 00:00:00,26.000000,53.000000,3.33,24.070000,15.500000,7.70,1.830,0.810000,8.37,1.000000,...,30.670000,87.000000,0.330000,37.00,11.000000,749.0,-0.13,0.83,0.0,23.50

Conclsuion : In this experiment we explored essential data analysis techniques like joins, data cleaning, rolling averages, and shifting. By merging datasets, fixing issues, and applying these methods, we uncovered valuable insights and trends. Mastering these skills helps turn raw data into meaningful, actionable information.